require File.expand_path(File.dirname(__FILE__) + '/../../spec_helper')

describe Admin::UsersController do
  integrate_views
  
  before :all do
    @user = User.create!(:username => 'betty', :password => 'crocker')
  end

  describe '#create' do
    before :each do
      post :create, :user => { :username => 'bill', :password => '' }
    end
    
    it 'should assign a new random password' do
      user = User.find_by_username 'bill'
      user.should_not be_nil
      user.password.should_not == ''
    end
  end
  
  describe '#new' do
    before :each do
      get :new
    end
    
    it 'should not show an input for password' do
      response.body.should match(/autogenerated/)
      response.body.should_not match(%r|<input[^>]*name="user\[password\]"|)
    end
  end
  
  describe '#edit' do
    before :each do
      get :edit, :id => @user.id
    end
    
    it 'should show the default text input for password' do
      response.body.should match(%r|<input[^>]*name="user\[password\]"|)
    end
  end
  
  describe '#update' do
    
    before :each do
      post :update, :id => @user.id, :user => {:username => 'bettie'}
    end
    
    it 'should not assign a new random password' do
      @user.reload
      @user.password.should == 'crocker'
    end
  end
end
