source 'http://rubygems.org'

gem 'rails', '3.0.6'

gem 'admin_assistant', :path => "../../admin_assistant"
gem 'paperclip', '2.3.11'
gem 'sqlite3'

group :development, :test do
  gem 'json'
  gem 'webrat', '>=0.7.2.pre', :git => 'http://github.com/kalv/webrat.git'
end
